#!/usr/bin/env python3

# Copyright 2019 Joakim Nilsson
#
# This file is part of tmx-to-snes.
#
# tmx-to-snes is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tmx-to-snes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tmx-to-snes.  If not, see <http://www.gnu.org/licenses/>.

#========
# Import
#========

import argparse as ap
import os
import xml.etree.ElementTree as et

#=================
# Parse arguments
#=================

# Make parser
parser = ap.ArgumentParser(description='Converts tiled Tiled tilemaps to SNES tilemaps.')
parser.add_argument(
	'filename',
	type = str,
	help = '.tmx file to convert.'
)
parser.add_argument(
	'-s',
	'--size',
	type     = int,
	choices  = [8, 16],
	help = 'Force side length of a tile in pixels instead of reading it from file.',
)
parser.add_argument(
	'-o',
	'--output-basename',
	type = str,
	help = 'Filename base for output files. Layer name and file extension will be appended.',
)
parser.add_argument(
	'-d',
	'--directory-format',
	action = 'store_true',
	help = 'Writes the output files in a directory specified by the output basename.',
)

# Parse
args = parser.parse_args()

#==============
# Convert file
#==============

# Parse .tmx file as XML data
root = et.parse(args.filename).getroot()

# Read tile size from file
if args.size is None:
	tile_width  = int(root.attrib['tilewidth'])
	tile_height = int(root.attrib['tilewidth'])
	if tile_width != tile_height:
		raise IOError('Tile width (%i) and height (%i) must be of the same size.' % (tile_width, tile_height))
	else:
		args.size = tile_width
		if args.size not in (8, 16):
			raise ValueError('Tile dimensions must either be 8 or 16')

# Default output basename
if args.output_basename is None:
	args.output_basename = os.path.splitext(args.filename)[0]

# Adjust output basename in case of (non-.maps) directory
if  os.path.isdir(args.output_basename) \
and os.path.splitext(args.output_basename)[1] != '.maps':
	args.output_basename = os.path.join(
		args.output_basename,
		os.path.split(os.path.splitext(args.filename)[0])[1],
	)

# Directory format
if args.directory_format:
	# Add extension if it is missing
	if os.path.splitext(args.output_basename)[1] != '.maps':
		args.output_basename += '.maps'

	# Make .maps directory
	try:
		os.mkdir(args.output_basename)

	# Touch if already exists
	except FileExistsError:
		os.utime(args.output_basename)

	# Add '/' to output basename
	args.output_basename = os.path.join(args.output_basename, '')

# File format
else:
	# Add '.' to output basename
	args.output_basename += '.'

# Use XML data to generate files
for layer_xml in root.iter('layer'):
	for data_xml in layer_xml.iter('data'):
		# Helper function
		def map_funct(x):
			x = int(x)-1        # tmx tiles are 1-indexed
			x *= args.size // 8 # Index step size = tile size / 8
			x = max(0, x)       # No tile results in tile 0

			# Each tile starts at a new 16-byte row
			if args.size == 16:
				hi_nibble = x & 0xf0
				lo_nibble = x & 0x0f
				x = (hi_nibble*2) | lo_nibble

			return x

		# Convert data
		data_bin = bytes(map(map_funct, data_xml.text.replace('\n', '').split(',')))

		# Write to output file
		filename_out = args.output_basename
		filename_out += layer_xml.attrib['name'] +'.map'
		with open(filename_out, 'wb') as file:
			file.write(data_bin)
